comm:
  command_port: 6002
  data_port: 6001
  device_addr: localhost  # bind digi to localhost port via ssh in terminal
  device_port: 2101       # local port bound to via ssh
  host: localhost
  method: ethernet
  sniffer_port: 6003



